HabitatMap/HabitatMap

- _includes/footer.html
- _sass/main.scss
- _sass/partials/_footer.scss
- _sass/partials/_forms.scss
- _sass/partials/_mixins.scss
- _sass/partials/_utilities.scss
- _sass/partials/_variables.scss
Basic style for newsletter input.
Label is hidden.
> Add basic styling for newsletter input

- _sass/config/_utilities.scss
- _sass/config/_variables.scss
- _sass/main.scss
- _sass/modules/_ac-intro.scss
- _sass/modules/_button.scss
- _sass/modules/_logo.scss
- _sass/modules/_panel.scss
- _sass/modules/_quote.scss
- _sass/modules/_split.scss
- _sass/modules/_typography.scss
- pages/index.md
Preparing Homepage accordingly to mockups.
> Homepage layout

- _includes/head.html
- _includes/header.html
- _sass/config/_mixins.scss
- _sass/modules/_header.scss
- assets/js/nav.js
> Toggle mobile menu

- _config.yml
- admin/config.yml
Set up categories and configure permalinks to posts.
> Add categories to blog posts

- _layouts/post.html
Show tags and category in blog post view. Not styled yet.
> Show category and tags in blog post

- Gemfile
- Gemfile.lock
- _config.yml
- _includes/category-nav.html
- _includes/post-group-header.html
- _includes/post-snippet.html
- _layouts/blog.html
- _layouts/category.html
- _layouts/post.html
- _sass/modules/_button.scss
> Category page

- _sass/config/_mixins.scss
- _sass/modules/_header.scss
Animations inspired by solution from https://www.memphisriverparks.org/parks/
> Nav animation

- pages/index.md
This serves also as an example how we can serve background images from Netlify Large Media responsively.
> Responsive hero bg image

- assets/js/algolia.js
- assets/js/faq.js
- assets/js/nav.js
- assets/js/posts.js
- assets/js/slider.js
- assets/js/sticky-header.js
Checked files with [es-check](https://github.com/dollarshaveclub/es-check) to be sure we comply to the standard.
> JS: use es5 since there is no transpiler

- _sass/config/_typography.scss
- _sass/main.scss
- _sass/modules/_read-more-button.scss
- assets/js/show-next.js
- pages/about/index.md
Needs some styling:
Also the two `<p>` should prolly have some space in between.
https://trello.com/c/C7mjtNXF/133-about-habitatmap-page-expand-collapse-text
> about/index: read more

- _config.yml
- _includes/analytics.html
- _includes/head.html
- bin/build.sh
Will need to replace `google_analytics` later on.
Docs (https://support.google.com/analytics/answer/1008080?hl=en#snippet).
> Basic google analytics

- _layouts/user_stories.html
- _user_stories/airparif.md
- _user_stories/children’s-environmental-literacy-foundation.md
- _user_stories/clean-air-carolina.md
- _user_stories/environmental-law-policy-center.md
- _user_stories/queensbridge-tech-lab.md
- _user_stories/usc-environmental-health-centers.md
- admin/config.yml
- pages/index.md
Adds an order fields and orders user stories accordingly, both on the user stories page and the slider on homepage.
https://trello.com/c/SsM9sLDa/165-user-stories-cms-provide-a-rank-order-field
> Order user stories

- _includes/map-screenshot.html
- assets/img/aircasting-map-screenshot-mobile.jpg
- assets/img/aircasting-map-screenshot.jpg
- assets/img/habitatmap-aircasting-map-screenshot.png
> Swap map screenshot, add mobile version

- _sass/modules/_shop-airbeam.scss
- pages/airbeam/buy-it-now.md
Changes arc position so that it intersects with image.
> Buy now arc

- 404.md
- _includes/algolia-scripts.html
- _layouts/search.html
- _sass/modules/_404.scss
> Add search bar on 404 page

- _sass/config/_header-theme.scss
- _sass/modules/_header.scss
Counterpart to https://github.com/HabitatMap/AirCasting/pull/399
> Tweak hovered/active nav links to improve legibility

- _sass/config/_typography.scss
- _sass/main.scss
- _sass/modules/_rotating-text.scss
- assets/js/rotating-text.js
- pages/index.md
Based on https://codepen.io/rachsmith/pen/BNKJme.
> Rotating text in hero section

- _sass/config/_typography.scss
- _sass/main.scss
- _sass/modules/_flipping-text.scss
- pages/index.md
The previous animation was causing a bug:
https://trello.com/c/SWobsDqL
> New animation

- _includes/paypal-button.html
- _sass/modules/_shop-airbeam.scss
- netlify/functions/paypal/paypal.js
- pages/airbeam/buy-it-now.md
Adds input and logic for applying a discount using a coupon code.
For testing visit: https://deploy-preview-193--habitatmap.netlify.app/airbeam/buy-it-now
> Promo code

- _includes/paypal-button.html
- _sass/modules/_shop-airbeam.scss
- netlify/functions/paypal/paypal.js
- pages/airbeam/buy-it-now.md
> Remove coupon code

- _sass/config/_header-theme.scss
- _sass/modules/_shop-airbeam.scss
- pages/airbeam/buy-it-now.md
- add description paragraph, 
- place AB3 and ABM in the same row on desktop, 
- add user guide buttons
> Update AB sales page
